# Change these first
owner: fencore # Your GitHub organization or username, where this repository lives
repo: zoner-upptime # The name of this repository

sites:
  - name: Freeport 11 - zoner.work
    url: https://zoner.work
  - name: Garbage Engine - zoner.gay
    url: https://zoner.gay
  - name: Garbage Cloud - nc.zoner.gay
    url: https://nc.zoner.gay
  - name: Garbage Collector - wf.zoner.gay
    url: https://wf.zoner.gay
  - name: Trash TV - oc.zoner.gay
    url: https://oc.zoner.gay

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.zoner.work
  # baseUrl: /your-repo-name
  logoUrl: https://i.zoner.work/firefish/favicon.png
  name: Zoner Hub
  introTitle: "**Service Monitor**"
  introMessage: This is a status page for services on the zoner.work and zoner.gay domains.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: night

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
